[phases.setup]
nixPkgs = [
  'php82', 
  'php82Extensions.mbstring',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.tokenizer',
  'php82Extensions.xml',
  'php82Extensions.ctype',
  'php82Extensions.fileinfo',
  'php82Extensions.curl',
  'php82Extensions.zip',
  'composer',
  'nodejs_20'
]

[phases.build]
cmds = [
  'composer install --no-dev --optimize-autoloader',
  'npm install',
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache',
  'php artisan migrate --force'
]

[start]
cmd = 'frankenphp -S 0.0.0.0:$PORT -t public'
